from lessons.dataTypes.lessonNumbers import lesson_integers, lesson_floats, lesson_numbers
from lessons.dataTypes.lessonBoolean import lesson_boolean, lesson_comparison_operators
from lessons.dataTypes.lessonsStrings import lesson_strings
from lessons.dataTypes.lessonsListTuples import lesson_list, lesson_tuple
from lessons.dataTypes.lessonsDict import lesson_dict
from lessons.dataTypes.lessonsSet import lesson_set
from lessons.dataTypes.lessonsRange import lesson_range

from lessons.controlFlow.ifElse import ifElse, isPositive, isEven
from lessons.controlFlow.forLoops import lesson_for_loops
from lessons.controlFlow.whileLoop import lesson_while_loop

from lessons.controlFlow.functionLessons import calcHt, addAll, display_person


print("Integers Lesson")
print("--------------------------------\n")

lesson_integers()
print("--------------------------------\n")
print("Floats Lesson")
print("--------------------------------\n")
lesson_floats()
print("--------------------------------\n")
print("Numbers Lesson")
print("--------------------------------\n")
lesson_numbers()
print("--------------------------------\n")
print("Boolean Lesson")
print("--------------------------------\n")
lesson_boolean()
print("--------------------------------\n")
print("Comparison Operators Lesson")
print("--------------------------------\n")
lesson_comparison_operators()

print("--------------------------------\n")
print("String Lesson")
print("--------------------------------\n")
lesson_strings()
print("--------------------------------\n")
print("List Lesson")
print("--------------------------------\n")
lesson_list()
print("--------------------------------\n")
print("Tuple Lesson")
print("--------------------------------\n")
lesson_tuple()
print("--------------------------------\n")
print("Dict Lesson")
print("--------------------------------\n")
lesson_dict()
print("--------------------------------\n")
print("Set Lesson")
print("--------------------------------\n")
lesson_set()
print("--------------------------------\n")
print("Range Lesson")
print("--------------------------------\n")
lesson_range()
print("--------------------------------\n")
print("If Else Lesson")
print("--------------------------------\n")
ifElse(4)
print("--------------------------------\n")
print("Is Positive Lesson")
print("--------------------------------\n")
isPositive(-10)
print("Is Positive Lesson")
print("--------------------------------\n")
isPositive(10)
print("Is Even Lesson")
print("--------------------------------\n")
isEven(10)
print("Is Even Lesson")
print("--------------------------------\n")
isEven(11)
print("--------------------------------\n")
print("For Loops Lesson")
print("--------------------------------\n")
lesson_for_loops()
print("--------------------------------\n")
print("While Loop Lesson")
print("--------------------------------\n")
lesson_while_loop()

print("--------------------------------\n")
print("Function Lesson")
print("--------------------------------\n")
print(calcHt(10, 20))
print("--------------------------------\n")
print("Add All Lesson")
print("--------------------------------\n")
print(addAll(1,2,3,4))
print("--------------------------------\n")
print("Display Person Lesson")
print("--------------------------------\n")
display_person(name="Rasil", age=20, city="Sydney", email="rasil@gmail.com")